### PR TITLE
Update Touch firmware to GT-I8190_EUR_JB_Opensource

### PR DESCRIPTION
**Pull request by kotzir**
Thanks to mativo @ XDA

*This fixes capacitive buttons, for those with older firmware in buttons

Change-Id: I24a9e75e8475f0d22d9ef5c8ca4e4b25d1f841a2

### CODE REVIEW

**Comment by golden-guy** [comment]
Has this been tested to work on either revision?

**Comment by kotzir** [comment]
According to @andi34 http://forum.xda-developers.com/showpost.php?p=65240906&postcount=122 yes they still work after the patch. But I only have an affected device, so I can't confirm myself.

**Comment by andi34** [comment]
Works fine on my golden, wasn't affected by the bug

**Comment by golden-guy** [comment]
Thanks, merged.

**Pull request merged**
